export const path = {
    homepage: '/',
    login: '/login',
    register: '/register',
    collections: '/collections',
    product: '/collections/:slug',
    brands: '/brands',
    exclusive: '/exclusive-online',
    membership: '/membership',
    blogs: '/blogs',
    account: '/account',
    orderHistory: "/account/order-history",
    orderHistoryDetail: "/account/order-history/:id",
    wishlist: "/account/wishlist",
    address: "/account/address",
    cart: "/cart",
    termsAndConditions: "/terms-and-conditions",
    pay: "/pay",
    deliveryPolicy: "/delivery-policy",
    paySuccess: "/paySuccess"
}